[package]
name = "maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
